- name: install via apk
  apk: name="{{ item }}" state=latest
  with_items:
    - bash
    - git
    - build-base
    - openssl
    - openssl-dev
    - yaml-dev
    - libffi-dev
    - linux-headers
    - readline-dev
    - zlib-dev
  become: yes
